Added fwutil High Level Design
nazariig/SONiC pull request #1
Opened 2019-08-23 14:14 UTC by nazariig

Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>

2019-09-09 22:15 UTC, nazariig commented
draft

2019-09-16 06:10 UTC, stephenxs requested changes

2019-09-16 06:10 UTC, stephenxs commented on doc/fwutil/fwutil.md
> +![Show components status flow](images/show_status_flow.svg "Figure 2: Show components status flow")
get_component_name_list is referenced but not defined in sonic_platform_base.

2019-09-16 06:10 UTC, stephenxs commented on doc/fwutil/fwutil.md
> +![FW install (non modular) flow](images/install_non_modular_flow.svg "Figure 3: FW install (non modular) flow")
install_component_firmware has been removed. Is itbetter to replace it with chassis.component[index].install_firmware?
Also, a flow which expresses how to map the components' name to their index is required.

2019-09-30 07:54 UTC, closed without merging